
version: "3"
services:

  backend:
      image: garugaru/coderdojo-app-backend
      ports:
        - 8089:80
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
      environment:
        EVENT_BRITE_TOKEN: ${EVENT_BRITE_TOKEN}